### ISSUE TITLE
[EDIT]

### ISSUE THREAD

**Issue by mechildezek** [molly/web3-is-going-great#376] opened 2022-05-30 14:05 UTC
# Entry
 May 23 Cawthorne post

# Changes

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* 
*

**Comment by molly** [comment] 2022-05-30 16:15
Not sure what the issue is here, maybe a dupe of #375? Feel free to reopen with more detail if there's an issue.

**Closed by molly** 2022-05-30 16:15 UTC
